// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYjtuJMPR50a5OPI_wmtLQkl6q9lv9hPU',
    appId: '1:845616940565:web:4ca462717fcb986bfb301c',
    messagingSenderId: '845616940565',
    projectId: 'desarrollo-movil-9c970',
    authDomain: 'desarrollo-movil-9c970.firebaseapp.com',
    databaseURL: 'https://desarrollo-movil-9c970-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollo-movil-9c970.firebasestorage.app',
    measurementId: 'G-KBMYNWR0YW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFpehURXiayErweazvO6cLSwMuk6jXJX0',
    appId: '1:845616940565:android:8e9a5226f7889b36fb301c',
    messagingSenderId: '845616940565',
    projectId: 'desarrollo-movil-9c970',
    databaseURL: 'https://desarrollo-movil-9c970-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollo-movil-9c970.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMJ6XovyJ752Peh74-4uM4Wt0Ue3sD1Mk',
    appId: '1:845616940565:ios:0fb1283157368693fb301c',
    messagingSenderId: '845616940565',
    projectId: 'desarrollo-movil-9c970',
    databaseURL: 'https://desarrollo-movil-9c970-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollo-movil-9c970.firebasestorage.app',
    iosBundleId: 'com.example.desMovilProyect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMJ6XovyJ752Peh74-4uM4Wt0Ue3sD1Mk',
    appId: '1:845616940565:ios:0fb1283157368693fb301c',
    messagingSenderId: '845616940565',
    projectId: 'desarrollo-movil-9c970',
    databaseURL: 'https://desarrollo-movil-9c970-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollo-movil-9c970.firebasestorage.app',
    iosBundleId: 'com.example.desMovilProyect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYjtuJMPR50a5OPI_wmtLQkl6q9lv9hPU',
    appId: '1:845616940565:web:a9d6082b8d9cee18fb301c',
    messagingSenderId: '845616940565',
    projectId: 'desarrollo-movil-9c970',
    authDomain: 'desarrollo-movil-9c970.firebaseapp.com',
    databaseURL: 'https://desarrollo-movil-9c970-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollo-movil-9c970.firebasestorage.app',
    measurementId: 'G-KBQBX42HGF',
  );

}